=== ParthenosWP4/standardsLibrary/Lexicography/ENeL-WG2/Kabakchi, The Dictionary of Russia/rd2.dtd
<!ENTITY % attrs "
	lang (en|ru) #IMPLIED
	class CDATA #IMPLIED
	style CDATA #IMPLIED
	version CDATA #IMPLIED
	id CDATA #IMPLIED
 ">

<!ENTITY % inline "
	b |
	i |
	SenseNumber |
	sup |
	sub |
	u
">

<!ELEMENT Note (#PCDATA|%inline;)*>
<!ELEMENT sub (#PCDATA|%inline;)*>
<!ELEMENT sup (#PCDATA|%inline;)*>
<!ELEMENT u (#PCDATA|%inline;)*>



<!ELEMENT b (#PCDATA|%inline;)*>

<!ELEMENT i (#PCDATA|%inline;)*>
<!ATTLIST i
	%attrs;
>

<!-- ============ Entry ========= -->
<!ELEMENT Dictionary (Entry)+>
<!ATTLIST Dictionary
	version CDATA #IMPLIED
	%attrs;
>

<!ELEMENT Entry (DictionaryEntry, SubEntry*)>
<!ATTLIST Entry
	hw CDATA #IMPLIED
	pos CDATA #IMPLIED
	identifier CDATA #REQUIRED
	%attrs;
>

<!ELEMENT DictionaryEntry (
	(HeadwordBlock,
	SenseGrp*,
	(SeeAlso|See)?)|
	(HeadwordBlock,XRef?)
)>
<!ATTLIST DictionaryEntry
	identifier CDATA #IMPLIED
	%attrs;
>


<!-- ============ SubEntry ========= -->
<!ELEMENT SubEntry (
	SubHeadwordBlock,
	SenseGrp*,
	(SeeAlso|See)?,
    XRef?
  )>
<!ELEMENT SubHeadwordBlock (
	SubHeadwordCtn+,	
	PartOfSpeech*,
	(SeeAlso|See)?,
	VariantFormBlock?
)>
<!-- ========= SubHeadword ========== -->
<!ELEMENT SubHeadwordCtn (
	SubHeadword,
	AlternativeScripting*,
	SubjectField?,
	Register?
)>

<!ATTLIST SubHeadwordCtn
	%attrs;
>
<!ELEMENT SubHeadword (#PCDATA|%inline;)*>


<!-- ========= Headword ========== -->
<!ELEMENT HeadwordBlock (
	HeadwordCtn+,	
	PartOfSpeech*,
	(SeeAlso|See)?,
	VariantFormBlock?
)>

<!ELEMENT HeadwordCtn (
	Headword,
	AlternativeScripting*,
	SubjectField?,
	Register?)>
	
<!ELEMENT AlternativeScripting (#PCDATA|%inline;)*>
<!ATTLIST AlternativeScripting
modifier (also|usually|frequently|traditionally|dated|literally) #IMPLIED
freeType CDATA #IMPLIED
%attrs;
>

<!ATTLIST HeadwordCtn
	%attrs;
>
<!ELEMENT Headword (#PCDATA|%inline;)*>

<!-- ============ VariantForm ================ -->
<!ELEMENT VariantFormBlock (VariantFormCtn+)>

<!ELEMENT VariantFormCtn (
VariantForm,
AlternativeTranslit*
)>
<!ATTLIST VariantFormCtn
	%attrs;
>
<!ELEMENT VariantForm (#PCDATA|%inline;)*>

<!ELEMENT AlternativeTranslit (#PCDATA|%inline;)*>

<!-- ============ SenseGrp ================ -->
<!ELEMENT SenseGrp (
	SenseNumber?,	
	SubjectField*,
	Register*,
	DefinitionCtn?,
	(GeographicalUsage|UsageNote)*,
	CitationCtn?,
	SeeAlso?) 
>
<!ATTLIST SenseGrp 
   identifier CDATA #IMPLIED
   version CDATA #IMPLIED
   >
   
<!ELEMENT SenseNumber EMPTY>
<!ATTLIST SenseNumber
	value (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|notPredefined) #REQUIRED
	freeValue CDATA #IMPLIED
>
   
<!--  =============Definition  ========== -->

<!ELEMENT Definition (#PCDATA|%inline;)*>
<!ATTLIST Definition
	identifier CDATA #IMPLIED
	%attrs;
>
<!ELEMENT DefinitionCtn (
	Definition,
	AlternativeScripting?,
	GraphicIllustration?,
	Note*
)>
<!ATTLIST DefinitionCtn
	%attrs;
>

<!ELEMENT GraphicIllustration (#PCDATA|%inline;)*>


<!--  ============= Citation  ========== -->
<!ELEMENT CitationCtn (
	Citation+,
	AlternativeScripting*, 
	CitationSourceCtn*
)>
<!ATTLIST CitationCtn
ID CDATA #IMPLIED
	%attrs;
>
<!ELEMENT Citation (#PCDATA|%inline;)*>

<!ELEMENT CitationSourceCtn (
	CitationSource+,
	CitationAuthor+
)>
<!ELEMENT CitationSource (#PCDATA|%inline;)*>

<!ELEMENT CitationAuthor (#PCDATA|%inline;)*>

<!-- ============ Usage ========== -->
<!ELEMENT GeographicalUsage EMPTY>
<!ATTLIST GeographicalUsage
	modifier (also|especially|not|only|usually) #IMPLIED
	value (notPredefined|US|Brit|Canada|Austr) #REQUIRED
	freeValue CDATA #IMPLIED
>

<!ELEMENT UsageNote EMPTY>
<!ATTLIST UsageNote
	modifier (also|especially|not|only|usually) #IMPLIED
	value (notPredefined|US|Brit|Russ) #REQUIRED
	freeValue CDATA #IMPLIED
>


<!-- ========== References ========== -->
<!ELEMENT SeeAlso (#PCDATA|%inline;)*>
<!ATTLIST SeeAlso
	Ptr IDREF #IMPLIED
	%attrs;
>

<!ELEMENT See (#PCDATA|%inline;)*>
<!ATTLIST See
	Ptr IDREF #IMPLIED
	%attrs;
>
<!ELEMENT XRef (#PCDATA|%inline;)*>
<!ATTLIST XRef
	Ptr IDREF #IMPLIED
	%attrs;
>

	
	
<!-- ========== PartOfSpeech ========== -->	
<!ELEMENT PartOfSpeech EMPTY>
<!ATTLIST PartOfSpeech
	value (notPredefined|
		abbreviation|
		adjective|
		adverb|
		conjunction|
		initials|
		interjection|
		noun|
		number|
		numeral|
		participle|
		particle|
		phrase|
		preposition|
		prefix|
		pronoun|
		suffix|
		verb|
		letter) #REQUIRED
	freeValue CDATA #IMPLIED
>

<!-- ========== SubjectField ========== -->

<!ELEMENT SubjectField EMPTY>
<!ATTLIST SubjectField
	modifier (also|usually|especially) #IMPLIED
	value (
notPredefined|
administration|
aeronautics|
agriculture|
anatomy|
anthropology|
archeology|
architecture|
art|
astrology|
astronomy|
automobiles|
aviation|
biology|
botanics|
chemistry|
cinema|
clothing|
commerce|
computers|
construction|
culinary|
dress|
ecology|
economics|
education|
electricity|
electronics|
environment|
finance|
games|
geography|
geology|
geometry|
grammar|
history|
internet|
journalism|
law|
linguistics|
literature|
mathematics|
mechanics|
medicine|
meteorology|
military|
music|
mythology|
nautical|
pharmacology|
philosophy|
photography|
physics|
physiology|
politics|
psychology|
radio|
rail|
religion|
school|
sociology|
sport|
technical|
technology|
telecommunication|
telephone|
television|
theatre|
theology|
transportation|
university|
zoology|
geographical|
historical|
religious|
musical|
folklore|
arts|
science|
name|
place-name|
etnonym|
tradition|
transport|
Soviet-ideology|
ethnonym) #REQUIRED
	freeValue CDATA #IMPLIED
	%attrs;
>

<!-- ========== Register ========== -->	
<!ELEMENT Register EMPTY>
<!ATTLIST Register
	value (
	notPredefined|
	colloquial|pejorative|
	euphemistic|
	familiar|formal|
	impolite|informal|
	literary|obsolete|
	offensive|official|
	old-fashioned|
	spoken|technical|
	vulgar|slang|
	archaic|disputed|
	metaphorical-use) #REQUIRED
	freeValue CDATA #IMPLIED
	modifier CDATA #IMPLIED
>

=== ParthenosWP4/standardsLibrary/Lexicography/ENeL-WG2/Kabakchi, The Dictionary of Russia/boyar.xml
<!DOCTYPE Entry SYSTEM "rd2.dtd">
<Entry identifier="EN00000270">
    <DictionaryEntry identifier="DE00000269">
      <HeadwordBlock>
        <HeadwordCtn>
          <Headword>boyar</Headword>

          <SubjectField value="historical" />
        </HeadwordCtn>

        <PartOfSpeech value="noun" />

        <VariantFormBlock>
          <VariantFormCtn>
            <VariantForm>боярин</VariantForm>

            <AlternativeTranslit><i>boyarin</i></AlternativeTranslit>
          </VariantFormCtn>
        </VariantFormBlock>
      </HeadwordBlock>

      <SenseGrp>
        <DefinitionCtn>
          <Definition>a member of medieval Russia's aristocracy, before Peter
          the Great.</Definition>
        </DefinitionCtn>

        <CitationCtn>
          <Citation>Boris [Sheremetev] was the last of old <i>boyars</i>, the
          leading noblemen of Muscovy whose wealth and power derived from the
          favour of the Tsar (they had all but disappeared by the end of
          Peter's reign as newly titled nobles superseded them</Citation>

          <CitationSourceCtn>
            <CitationSource>(Figes, 2002, p.15)</CitationSource>

            <CitationAuthor></CitationAuthor>
          </CitationSourceCtn>
        </CitationCtn>
      </SenseGrp>
    </DictionaryEntry>

    <SubEntry>
      <SubHeadwordBlock>
        <SubHeadwordCtn>
          <SubHeadword>Boyar Duma</SubHeadword>

          <SubjectField value="historical" />
        </SubHeadwordCtn>

        <PartOfSpeech value="phrase" />

        <VariantFormBlock>
          <VariantFormCtn>
            <VariantForm>Боярская дума</VariantForm>

            <AlternativeTranslit><i>Boyarskaya Duma</i></AlternativeTranslit>
          </VariantFormCtn>
        </VariantFormBlock>
      </SubHeadwordBlock>

      <SenseGrp>
        <DefinitionCtn>
          <Definition>a consultative body in Kievan Rus’ and medieval
          Russia.</Definition>
        </DefinitionCtn>

        <CitationCtn>
          <Citation>The boyars formed a boyar council, or <i>duma</i>, which
          advised the prince in important matters of state</Citation>

          <CitationSourceCtn>
            <CitationSource>(<i>Encycl.Brit.</i>, 2005)</CitationSource>

            <CitationAuthor></CitationAuthor>
          </CitationSourceCtn>
        </CitationCtn>
      </SenseGrp>
    </SubEntry>

    <SubEntry>
      <SubHeadwordBlock>
        <SubHeadwordCtn>
          <SubHeadword><i>boyarynya</i></SubHeadword>

          <SubjectField value="historical" />
        </SubHeadwordCtn>

        <PartOfSpeech value="noun" />

        <VariantFormBlock>
          <VariantFormCtn>
            <VariantForm>боярыня</VariantForm>
          </VariantFormCtn>
        </VariantFormBlock>
      </SubHeadwordBlock>

      <SenseGrp>
        <DefinitionCtn>
          <Definition>boyar's wife.</Definition>
        </DefinitionCtn>

        <CitationCtn>
          <Citation>[The Tsar’s bride] was then turned over to the sisters and
          close female relatives of the tsar and to the noble ladies, the
          boyarinas</Citation>

          <CitationSourceCtn>
            <CitationSource>(Massie, 1980, p.50)</CitationSource>

            <CitationAuthor></CitationAuthor>
          </CitationSourceCtn>
        </CitationCtn>
      </SenseGrp>

      <SeeAlso>Boyarynya Morozova</SeeAlso>
    </SubEntry>
  </Entry>
