=== ParthenosWP4/standardsLibrary/Lexicography/ENeL-WG2/Dictionary Samples/Svenska Akademiens Ordbok/saobexport.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
        xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- Schema för beskrivning av SAOB export. -->
	<!-- Erik Bäckerud, 2014-10-08 -->
	<!-- 2014-11-18, E.B.: -->
	<!-- titel valfritt attribut på rotord. -->
	<!-- Homografsiffra kan nu vara sträng. (tillåter "1-2" osv) -->
	<!-- -->
	<!-- targetNamespace="http://www.saob.se/saobexport" xmlns="http://www.saob.se/saobexport"
		-->
	
	<!-- Rotelementet, alla dokument innehåller ett <artikel> element. -->
	<xs:element name="artikel">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="meta" />
				<xs:element ref="body" />
				<xs:element ref="taggar" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="meta">
		<xs:complexType>
			<xs:attribute name="band" use="required" type="xs:integer" />
			<xs:attribute name="fil" use="required" type="xs:string" />
			<xs:attribute name="hänvisning" use="required" type="xs:boolean" />
			<xs:attribute name="spalt" use="required" type="SaobSpaltnamnsTyp" />
			<xs:attribute name="titel" use="required" type="xs:string" />
			<xs:attribute name="unik" use="required" type="xs:NCName" />
			<xs:attribute name="version" use="required" type="xs:NMTOKEN" />
		</xs:complexType>
	</xs:element>
	
	<!-- "body" innehåller en kopia av originaltexten, en följd av STYCKE-element. -->
	<xs:element name="body">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" name="STYCKE" type="StyckeTyp" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!-- Här börjar definitionen av STYCKE och dess dotterelement. -->
	<!-- ************************************************************** -->
	
	<xs:complexType name="StyckeTyp">
		<xs:sequence>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:group ref="StyckeGrupp" />
			</xs:sequence>
			<xs:sequence maxOccurs="unbounded" minOccurs="0">
				<xs:element name="b" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="id" type="SaobIdTyp" use="required" />
						<xs:attribute name="nyrad" type="xs:boolean" default="false" />
					</xs:complexType>
				</xs:element>
				<xs:group ref="StyckeGrupp" maxOccurs="1" minOccurs="1" />
			</xs:sequence>
		</xs:sequence>
		<xs:attribute name="id" type="SaobIdTyp" use="required" />
		<xs:attributeGroup ref="ArtStart" />
	</xs:complexType>
	
	<xs:simpleType name="SaobIdTyp">
		<xs:restriction base="xs:NCName">
			<xs:pattern value="\S+" />
			<!-- vad är bäst restriktion? -->
		</xs:restriction>
	</xs:simpleType>
	
	<xs:group name="StyckeGrupp">
		<xs:choice>
			<xs:element name="Formstil" type="StilelementTyp" />
			<xs:element name="Forfattarstil" type="StilelementTyp" />
			<xs:element name="LitenAntikva" type="StilelementTyp" />
			<xs:element name="LitenGrekiska" type="StilelementTyp" />
			<xs:element name="LitenKursiv" type="StilelementTyp" />
			<xs:element name="LitenRubrik" type="StilelementTyp" />
			<xs:element name="StorAntikva" type="StilelementTyp" />
			<xs:element name="StorKursiv" type="StilelementTyp" />
			<xs:element name="StorGrekiska" type="StilelementTyp" />
			<xs:element name="StorRubrik" type="StilelementTyp" />
			<xs:element name="formparentes" type="StilelementTyp" />
		</xs:choice>
	</xs:group>
	
	<xs:complexType name="StilelementTyp">
		<xs:simpleContent>
			<xs:extension base="SvartSträngTyp">
				<xs:attribute name="rend" type="RendTyp" default="normal" />
				<xs:attribute name="nyspalt" type="SaobSpaltnamnsTyp" />
				<xs:attribute name="id" type="SaobIdTyp" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:attributeGroup name="ArtStart">
		<xs:attribute name="art" type="xs:string" />
		<xs:attribute name="hänvisning" type="xs:boolean" />
		<xs:attribute name="startspalt" type="SaobSpaltnamnsTyp" />
		<!-- svit saknas eller är 0 om detta ej är en svitartikel, annars anger "svit" viken
			artikel i ordning detta är. -->
		<xs:attribute name="svit" type="xs:integer" />
		<xs:attribute name="unik" type="xs:token" />
	</xs:attributeGroup>
	
	<xs:simpleType name="SvartSträngTyp">
		<xs:restriction base="xs:string">
		  <!-- <xs:pattern value="\S+" /> -->
		  <!-- Testar med alternativ definition av svartsträng -->
		  <!-- E.B. 14-11-28 -->
		  <xs:pattern value="[^ ]+" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="RendTyp">
		<xs:restriction base="xs:token">
			<xs:enumeration value="normal" />
			<xs:enumeration value="upphöjd" />
			<xs:enumeration value="nedsänkt" />
			<xs:enumeration value="spärrad" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="SaobSpaltnamnsTyp">
		<xs:restriction base="xs:NCName">
			<xs:pattern value="[A-ZÅÄÖ]\d+" />
		</xs:restriction>
	</xs:simpleType>
	
	<!-- Här slutar definitionen av STYCKE och dess dotterelement. -->
	<!-- ************************************************************** -->
	
	<xs:element name="taggar">
		<xs:complexType>
			<xs:choice>
				<xs:sequence>
					<xs:element ref="uppslagsord" />
					<xs:element ref="formparentes" minOccurs="0" />
					<xs:element ref="etymologi" minOccurs="0" />
					<xs:element ref="översikt" minOccurs="0" />
					<xs:element ref="definition" minOccurs="0" />
					<!-- Tillåt dess i avvikande ordning? -->
					<xs:choice minOccurs="0" maxOccurs="unbounded">
						<xs:element ref="förbindelser" />
						<xs:element ref="sammansättningar" />
						<xs:element ref="avledningar" />
					</xs:choice>
					<xs:element ref="anmärkningar" minOccurs="0" />
				</xs:sequence>
				<xs:sequence>
					<xs:element ref="hänvisning" minOccurs="1" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	
	<!-- StartSlut innebär att attributet start är obligatoriskt men slut är valfritt.
		-->
	<xs:attributeGroup name="StartSlut">
		<xs:attribute name="start" type="SaobIdTyp" use="required" />
		<xs:attribute name="slut" type="SaobIdTyp" />
	</xs:attributeGroup>
	
	<xs:simpleType name="ordklassTyp">
		<xs:restriction base="xs:token">
			<xs:enumeration value="substantiv" />
			<xs:enumeration value="adjektiv" />
			<xs:enumeration value="adverb" />
			<xs:enumeration value="pronomen" />
			<xs:enumeration value="bestämd artikel" />
			<xs:enumeration value="obestämd artikel" />
			<xs:enumeration value="räkneord" />
			<xs:enumeration value="preposition" />
			<xs:enumeration value="konjunktion" />
			<xs:enumeration value="infinitivmärke" />
			<xs:enumeration value="interjektion" />
			<xs:enumeration value="verb" />
			<xs:enumeration value="participiellt adjektiv" />
			<xs:enumeration value="partikel" />
			<xs:enumeration value="predikat" />
			<xs:enumeration value="sammansättningsförled" />
			<xs:enumeration value="prefix" />
			<xs:enumeration value="suffix" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:element name="uppslagsord">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="biform" />
			</xs:sequence>
			<xs:attribute name="ordklass" type="ordklassTyp" />
			<xs:attribute name="homografsiffra" type="xs:string" />
			<xs:attribute name="spalt" use="required" type="SaobSpaltnamnsTyp" />
			<xs:attribute name="titel" use="required" type="xs:string" />
			<xs:attributeGroup ref="StartSlut" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="hänvisning">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="biform" />
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="rotord" />
			</xs:sequence>
			<xs:attribute name="ordklass" type="ordklassTyp" />
			<xs:attribute name="homografsiffra" type="xs:string" />
			<xs:attribute name="spalt" use="required" type="SaobSpaltnamnsTyp" />
			<xs:attribute name="titel" use="required" type="xs:string" />
			<xs:attributeGroup ref="StartSlut" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="biform">
		<xs:complexType>
			<xs:attribute name="titel" use="required" type="xs:string" />
			<xs:attribute name="ordklass" type="ordklassTyp" />
			<xs:attribute name="homografsiffra" type="xs:string" />
			<xs:attributeGroup ref="StartSlut" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="rotord">
		<xs:complexType>
			<xs:attribute name="titel" type="xs:string" />
			<xs:attribute name="ordklass" type="ordklassTyp" />
			<xs:attribute name="homografsiffra" type="xs:string" />
			<xs:attributeGroup ref="StartSlut" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="formparentes">
		<xs:complexType>
			<xs:attribute name="start" type="SaobIdTyp" use="required" />
			<xs:attribute name="slut" type="SaobIdTyp" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="etymologi">
		<xs:complexType>
			<xs:attribute name="start" type="SaobIdTyp" use="required" />
			<xs:attribute name="slut" type="SaobIdTyp" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="översikt">
		<xs:complexType>
			<xs:attribute name="start" type="SaobIdTyp" use="required" />
			<xs:attribute name="slut" type="SaobIdTyp" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="definition">
		<xs:complexType>
			<xs:sequence>
				<xs:choice  minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="moment" />
					<xs:element ref="momentgrupp" />
				</xs:choice>
			</xs:sequence>
			<xs:attributeGroup ref="StartSlut" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="moment">
		<xs:complexType>
			<xs:sequence>
				<xs:choice  minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="moment" />
					<xs:element ref="momentgrupp" />
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="beteckning" type="xs:string" />
			<xs:attribute name="grupp" type="xs:string" />
			<xs:attribute name="nivå" use="required" type="xs:integer" />
			<xs:attribute name="start" type="SaobIdTyp" />
			<xs:attribute name="slut" type="SaobIdTyp" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="momentgrupp">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="moment" />
			</xs:sequence>
			<xs:attribute name="beteckning" type="xs:string" />
			<xs:attributeGroup ref="StartSlut" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="förbindelser">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="förbindelse" />
			</xs:sequence>
			<xs:attributeGroup ref="StartSlut" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="förbindelse">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="biform" />
				<xs:element minOccurs="0" ref="definition" />
				<!-- Särskilda förbindelser har inga sekundära särsk. förb., ssgr., eller avledn.
					-->
			</xs:sequence>
			<xs:attribute name="titel" use="required" />
			<xs:attribute name="ordklass" type="ordklassTyp" />
			<xs:attribute name="homografsiffra" type="xs:string" />
			<xs:attributeGroup ref="StartSlut" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="sammansättningar">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="ramsa" />
			</xs:sequence>
			<xs:attributeGroup ref="StartSlut" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="ramsa">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="sammansättning" />
			</xs:sequence>
			<xs:attribute name="beteckning" use="required" />
			<xs:attributeGroup ref="StartSlut" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="sammansättning">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="biform" />
				<xs:element ref="definition" minOccurs="0" />
				<xs:group minOccurs="0" maxOccurs="unbounded" ref="sekundära" />
			</xs:sequence>
			<xs:attribute name="ramsa" />
			<xs:attribute name="titel" use="required" type="xs:string" />
			<xs:attribute name="ordklass" type="ordklassTyp" />
			<xs:attribute name="homografsiffra" type="xs:string" />
			<xs:attributeGroup ref="StartSlut" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="avledningar">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="avledning" />
			</xs:sequence>
			<xs:attributeGroup ref="StartSlut" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="avledning">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="biform" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="definition" minOccurs="0" />
				<xs:group minOccurs="0" maxOccurs="unbounded" ref="sekundära" />
			</xs:sequence>
			<xs:attribute name="titel" use="required" type="xs:string" />
			<xs:attribute name="ordklass" type="ordklassTyp" />
			<xs:attribute name="homografsiffra" type="xs:string" />
			<xs:attributeGroup ref="StartSlut" />
		</xs:complexType>
	</xs:element>
	
	<xs:group name="sekundära">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="förbindelser" />
				<xs:element ref="avledningar" />
				<xs:element ref="sammansättningar" />
			</xs:choice>
		</xs:sequence>
	</xs:group>
	
	<!-- Anmärkningar kan förekomma var som helst i texten -->
	<!-- men i XML:en är de samlade här.                   -->
	<xs:element name="anmärkningar">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="anmärkning" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="anmärkning">
		<xs:complexType>
			<!-- För en anmärkning måste både start och slut anges. -->
			<xs:attribute name="start" type="SaobIdTyp" use="required" />
			<xs:attribute name="slut" type="SaobIdTyp" use="required" />
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== ParthenosWP4/standardsLibrary/Lexicography/ENeL-WG2/Dictionary Samples/Svenska Akademiens Ordbok/T_0185-0310_00083.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><artikel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="saobexport.xsd">
  <meta band="33" fil="T_0185-0310.xml" hänvisning="false" spalt="T288" titel="TALANG" unik="T_0185-0083.s2ii" version="2015-04-20T11:52:13"/>
  <body>
    <STYCKE art="TALANG" hänvisning="false" id="T185_123559" startspalt="T288" unik="T_0185-0083.s2ii">
      <StorRubrik id="T185_123560">TALANG</StorRubrik>
      <b id="T185_123561"/>
      <StorKursiv id="T185_123562">talaŋ</StorKursiv>
      <StorAntikva id="T185_123563" rend="upphöjd">4</StorAntikva>
      <LitenAntikva id="T185_123564">,</LitenAntikva>
      <b id="T185_123565"/>
      <LitenAntikva id="T185_123566">r.</LitenAntikva>
      <b id="T185_123567"/>
      <LitenAntikva id="T185_123568">l.</LitenAntikva>
      <b id="T185_123569"/>
      <LitenAntikva id="T185_123570">m.;</LitenAntikva>
      <b id="T185_123571"/>
      <LitenAntikva id="T185_123572">best.</LitenAntikva>
      <b id="T185_123573"/>
      <Formstil id="T185_123574">-en</Formstil>
      <LitenAntikva id="T185_123575">;</LitenAntikva>
      <b id="T185_123576"/>
      <LitenAntikva id="T185_123577">pl.</LitenAntikva>
      <b id="T185_123578"/>
      <Formstil id="T185_123579">-er</Formstil>
      <b id="T185_123580"/>
      <LitenAntikva id="T185_123581">(</LitenAntikva>
      <Forfattarstil id="T185_123582">Kellgren</Forfattarstil>
      <b id="T185_123583"/>
      <LitenKursiv id="T185_123584">(SVS)</LitenKursiv>
      <b id="T185_123585"/>
      <LitenAntikva id="T185_123586">4:</LitenAntikva>
      <b id="T185_123587"/>
      <LitenAntikva id="T185_123588">164</LitenAntikva>
      <b id="T185_123589"/>
      <Formstil id="T185_123590">(1780)</Formstil>
      <b id="T185_123591"/>
      <LitenAntikva id="T185_123592">osv.)</LitenAntikva>
      <b id="T185_123593"/>
      <formparentes id="T185_123594">(</formparentes>
      <StorAntikva id="T185_123595">(†)</StorAntikva>
      <b id="T185_123596"/>
      <Formstil id="T185_123597">-s</Formstil>
      <b id="T185_123598"/>
      <Forfattarstil id="T185_123599">Tersmeden</Forfattarstil>
      <b id="T185_123600"/>
      <LitenKursiv id="T185_123601">Mem.</LitenKursiv>
      <b id="T185_123602"/>
      <LitenAntikva id="T185_123603">2:</LitenAntikva>
      <b id="T185_123604"/>
      <LitenAntikva id="T185_123605">280</LitenAntikva>
      <b id="T185_123606"/>
      <Formstil id="T185_123607">(</Formstil>
      <LitenKursiv id="T185_123608">c.</LitenKursiv>
      <b id="T185_123609"/>
      <Formstil id="T185_123610">1790)</Formstil>
      <LitenAntikva id="T185_123611">,</LitenAntikva>
      <b id="T185_123612"/>
      <LitenKursiv id="T185_123613">Därs.</LitenKursiv>
      <b id="T185_123614"/>
      <LitenAntikva id="T185_123615">6:</LitenAntikva>
      <b id="T185_123616"/>
      <LitenAntikva id="T185_123617">163</LitenAntikva>
      <formparentes id="T185_123618">)</formparentes>
      <LitenAntikva id="T185_123619">;</LitenAntikva>
      <b id="T185_123620"/>
      <LitenAntikva id="T185_123621">äv.</LitenAntikva>
      <b id="T185_123622"/>
      <LitenAntikva id="T185_123623">(numera</LitenAntikva>
      <b id="T185_123624"/>
      <LitenAntikva id="T185_123625">mindre</LitenAntikva>
      <b id="T185_123626"/>
      <LitenAntikva id="T185_123627">br.)</LitenAntikva>
      <b id="T185_123628"/>
      <LitenRubrik id="T185_123629">TALENT</LitenRubrik>
      <b id="T185_123630"/>
      <StorKursiv id="T185_123631" nyspalt="T289">talän</StorKursiv>
      <StorAntikva id="T185_123632" rend="upphöjd">4</StorAntikva>
      <StorKursiv id="T185_123633">t</StorKursiv>
      <b id="T185_123634"/>
      <LitenAntikva id="T185_123635">l.</LitenAntikva>
      <b id="T185_123636"/>
      <StorKursiv id="T185_123637">talaŋ</StorKursiv>
      <StorAntikva id="T185_123638" rend="upphöjd">4</StorAntikva>
      <b id="T185_123639"/>
      <LitenAntikva id="T185_123640">l.</LitenAntikva>
      <b id="T185_123641"/>
      <LitenAntikva id="T185_123642">med</LitenAntikva>
      <b id="T185_123643"/>
      <LitenAntikva id="T185_123644">mer</LitenAntikva>
      <b id="T185_123645"/>
      <LitenAntikva id="T185_123646">l.</LitenAntikva>
      <b id="T185_123647"/>
      <LitenAntikva id="T185_123648">mindre</LitenAntikva>
      <b id="T185_123649"/>
      <LitenAntikva id="T185_123650">genuint</LitenAntikva>
      <b id="T185_123651"/>
      <LitenAntikva id="T185_123652">franskt</LitenAntikva>
      <b id="T185_123653"/>
      <LitenAntikva id="T185_123654">uttal,</LitenAntikva>
      <b id="T185_123655"/>
      <LitenAntikva id="T185_123656">sbst.</LitenAntikva>
      <StorAntikva id="T185_123657" rend="upphöjd">1</StorAntikva>
      <LitenAntikva id="T185_123658">,</LitenAntikva>
      <b id="T185_123659"/>
      <LitenAntikva id="T185_123660">r.</LitenAntikva>
      <b id="T185_123661"/>
      <LitenAntikva id="T185_123662">l.</LitenAntikva>
      <b id="T185_123663"/>
      <LitenAntikva id="T185_123664">m.;</LitenAntikva>
      <b id="T185_123665"/>
      <LitenAntikva id="T185_123666">best.</LitenAntikva>
      <b id="T185_123667"/>
      <Formstil id="T185_123668">-en</Formstil>
      <LitenAntikva id="T185_123669">;</LitenAntikva>
      <b id="T185_123670"/>
      <LitenAntikva id="T185_123671">pl.</LitenAntikva>
      <b id="T185_123672"/>
      <Formstil id="T185_123673">-er</Formstil>
      <b id="T185_123674"/>
      <LitenAntikva id="T185_123675">(</LitenAntikva>
      <LitenKursiv id="T185_123676">2RARP</LitenKursiv>
      <b id="T185_123677"/>
      <LitenAntikva id="T185_123678">18:</LitenAntikva>
      <b id="T185_123679"/>
      <LitenAntikva id="T185_123680">Bil.</LitenAntikva>
      <b id="T185_123681"/>
      <LitenAntikva id="T185_123682">410</LitenAntikva>
      <b id="T185_123683"/>
      <Formstil id="T185_123684">(1751)</Formstil>
      <b id="T185_123685"/>
      <LitenAntikva id="T185_123686">osv.)</LitenAntikva>
      <b id="T185_123687"/>
      <formparentes id="T185_123688">(</formparentes>
      <StorAntikva id="T185_123689">(†)</StorAntikva>
      <b id="T185_123690"/>
      <Formstil id="T185_123691">-s</Formstil>
      <b id="T185_123692"/>
      <Forfattarstil id="T185_123693">Rodhe</Forfattarstil>
      <b id="T185_123694"/>
      <LitenKursiv id="T185_123695">Lindblom</LitenKursiv>
      <b id="T185_123696"/>
      <LitenAntikva id="T185_123697">11</LitenAntikva>
      <b id="T185_123698"/>
      <Formstil id="T185_123699">(</Formstil>
      <LitenKursiv id="T185_123700">cit.</LitenKursiv>
      <b id="T185_123701"/>
      <LitenKursiv id="T185_123702">fr.</LitenKursiv>
      <b id="T185_123703"/>
      <Formstil id="T185_123704">1764)</Formstil>
      <LitenAntikva id="T185_123705">,</LitenAntikva>
      <b id="T185_123706"/>
      <LitenKursiv id="T185_123707">BrinkmArch.</LitenKursiv>
      <b id="T185_123708"/>
      <LitenAntikva id="T185_123709">2:</LitenAntikva>
      <b id="T185_123710"/>
      <LitenAntikva id="T185_123711">461</LitenAntikva>
      <b id="T185_123712"/>
      <Formstil id="T185_123713">(1795)</Formstil>
      <formparentes id="T185_123714">)</formparentes>
      <b id="T185_123715"/>
      <formparentes id="T185_123716">(</formparentes>
      <Formstil id="T185_123717">talang</Formstil>
      <b id="T185_123718"/>
      <Formstil id="T185_123719">1780</Formstil>
      <b id="T185_123720"/>
      <LitenAntikva id="T185_123721">osv.</LitenAntikva>
      <b id="T185_123722"/>
      <Formstil id="T185_123723">talant-</Formstil>
      <b id="T185_123724"/>
      <LitenAntikva id="T185_123725">i</LitenAntikva>
      <b id="T185_123726"/>
      <LitenAntikva id="T185_123727">ssg</LitenAntikva>
      <b id="T185_123728"/>
      <Formstil id="T185_123729">1829</Formstil>
      <LitenAntikva id="T185_123730">.</LitenAntikva>
      <b id="T185_123731"/>
      <Formstil id="T185_123732">talens</Formstil>
      <LitenAntikva id="T185_123733">,</LitenAntikva>
      <b id="T185_123734"/>
      <LitenAntikva id="T185_123735">pl.</LitenAntikva>
      <b id="T185_123736"/>
      <Formstil id="T185_123737">1764</Formstil>
      <LitenAntikva id="T185_123738">.</LitenAntikva>
      <b id="T185_123739"/>
      <Formstil id="T185_123740">talent</Formstil>
      <b id="T185_123741"/>
      <Formstil id="T185_123742">1717</Formstil>
      <LitenAntikva id="T185_123743">—</LitenAntikva>
      <Formstil id="T185_123744">1976</Formstil>
      <formparentes id="T185_123745">)</formparentes>
      <b id="T185_123746"/>
      <StorAntikva id="T185_123747">[</StorAntikva>
      <LitenAntikva id="T185_123748">jfr</LitenAntikva>
      <b id="T185_123749"/>
      <LitenAntikva id="T185_123750">t.</LitenAntikva>
      <b id="T185_123751"/>
      <LitenKursiv id="T185_123752">talent</LitenKursiv>
      <LitenAntikva id="T185_123753">,</LitenAntikva>
      <b id="T185_123754"/>
      <LitenAntikva id="T185_123755">eng.</LitenAntikva>
      <b id="T185_123756"/>
      <LitenKursiv id="T185_123757">talent</LitenKursiv>
      <LitenAntikva id="T185_123758">;</LitenAntikva>
      <b id="T185_123759"/>
      <LitenAntikva id="T185_123760">av</LitenAntikva>
      <b id="T185_123761"/>
      <LitenAntikva id="T185_123762">fr.</LitenAntikva>
      <b id="T185_123763"/>
      <LitenKursiv id="T185_123764">talent</LitenKursiv>
      <LitenAntikva id="T185_123765">;</LitenAntikva>
      <b id="T185_123766"/>
      <LitenAntikva id="T185_123767">eg.</LitenAntikva>
      <b id="T185_123768"/>
      <LitenAntikva id="T185_123769">bildl.</LitenAntikva>
      <b id="T185_123770"/>
      <LitenAntikva id="T185_123771">anv.</LitenAntikva>
      <b id="T185_123772"/>
      <LitenAntikva id="T185_123773">av</LitenAntikva>
      <b id="T185_123774"/>
